# Generated by Django 5.1.7 on 2025-03-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemshopping',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemshopping',
            name='marketName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
