# Generated by Django 5.1.7 on 2025-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_list_listname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AddField(
            model_name='list',
            name='item',
            field=models.ManyToManyField(related_name='lists', to='list.itemshopping'),
        ),
    ]
