# Generated by Django 5.1.7 on 2025-04-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_list_item_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSerie',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='list.item')),
                ('type', models.CharField(choices=[('serie', 'SERIE')], default='serie', max_length=10)),
                ('season', models.IntegerField(default=1)),
                ('episode', models.IntegerField(default=1)),
                ('website', models.CharField(default='', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('list.item',),
        ),
        migrations.CreateModel(
            name='SerieInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1)),
                ('episode', models.IntegerField(default=0)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.itemserie')),
            ],
        ),
        migrations.CreateModel(
            name='ListSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.user')),
                ('item', models.ManyToManyField(related_name='lists', to='list.serieinfouser')),
            ],
        ),
    ]
