# Generated by Django 5.1.7 on 2025-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_itemserie_serieinfouser_listseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemserie',
            name='website',
            field=models.CharField(default='', max_length=80),
        ),
    ]
