# Generated by Django 5.1.7 on 2025-04-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_alter_item_name_alter_itemserie_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='serieinfouser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serieinfouser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListSeries',
        ),
    ]
