# Generated by Django 5.1.7 on 2025-04-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_serieinfouser_updated_at_serieinfouser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='listName',
        ),
    ]
